POST http://localhost:8000/api/v2/tenants/default_tenant/databases/default_database/collections/fc688e67-ad04-40d5-82c9-75041e06638c/get
Content-Type: application/json

{
  "limit": 5,
  "include": ["documents", "metadatas","embeddings"]
}

###

GET http://localhost:8000/api/v2/tenants/default_tenant/databases/default_database/collections


###26a71a8b-fff4-4596-a0fb-651ba917cc6e

POST http://localhost:8000/api/v2/tenants/default_tenant/databases/default_database/collections/26a71a8b-fff4-4596-a0fb-651ba917cc6e/get
Content-Type: application/json

{
  "limit": 5,
  "include": ["documents", "metadatas","embeddings"]
}